// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoe_restoration_project.Context;

#nullable disable

namespace Shoe_restoration_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817174533_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shoe_restoration_project.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex(new[] { "Name" }, "IX_Brands_Name")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_Colors_Name")
                        .IsUnique();

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_Conditions_Name")
                        .IsUnique();

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("IsoCode")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IsoCode" }, "IX_Countries_IsoCode")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "IX_Countries_Name")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.MeasurementMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Name")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_MeasurementMetrics_Name")
                        .IsUnique();

                    b.ToTable("MeasurementMetrics");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.MeasurementProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_MeasurementProperties_Name")
                        .IsUnique();

                    b.ToTable("MeasurementProperties");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.MeasurementValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MeasurementMetricId")
                        .HasColumnType("int")
                        .HasColumnName("MeasurementPropertyId");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementMetricId");

                    b.HasIndex(new[] { "Value" }, "IX_MeasurementValues_Name")
                        .IsUnique();

                    b.ToTable("MeasurementValues");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.Shoe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("BrandId");

                    b.Property<int>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("ColorId");

                    b.Property<int>("ConditionId")
                        .HasColumnType("int")
                        .HasColumnName("ConditionId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("Description");

                    b.Property<int>("ShoeTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ShoeTypeId");

                    b.Property<int>("SizeId")
                        .HasColumnType("int")
                        .HasColumnName("SizeId");

                    b.Property<int>("SkinTypeId")
                        .HasColumnType("int")
                        .HasColumnName("SkinTypeId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ConditionId");

                    b.HasIndex("ShoeTypeId");

                    b.HasIndex("SizeId");

                    b.HasIndex("SkinTypeId");

                    b.HasIndex(new[] { "BrandId" }, "IX_Shoes_BrandId");

                    b.HasIndex(new[] { "Title" }, "IX_Shoes_Title")
                        .IsUnique();

                    b.ToTable("Shoes");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.ShoeImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("(newsequentialid())", "DF_ShoeImages_Id");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("ImageData");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<int>("ShoeId")
                        .HasColumnType("int")
                        .HasColumnName("ShoeId");

                    b.HasKey("Id")
                        .HasName("PK__Shoe_Ima__3214EC07501FBD4C");

                    b.HasIndex(new[] { "Name" }, "IX_ShoeImages_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "ShoeId" }, "IX_ShoeImages_ShoeId");

                    b.ToTable("ShoeImages");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.ShoeMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MeasurementPropertyId")
                        .HasColumnType("int")
                        .HasColumnName("MeasurementPropertyId");

                    b.Property<int>("MeasurementValueId")
                        .HasColumnType("int")
                        .HasColumnName("MeasurementValueId");

                    b.Property<int>("ShoeId")
                        .HasColumnType("int")
                        .HasColumnName("ShoeId");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementPropertyId");

                    b.HasIndex("MeasurementValueId");

                    b.HasIndex("ShoeId");

                    b.ToTable("ShoeMeasurements");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.ShoeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_ShoeTypes_Name")
                        .IsUnique();

                    b.ToTable("ShoeTypes");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SizeMetricId")
                        .HasColumnType("int")
                        .HasColumnName("SizeMetricId");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("PK_Shoe_Sizes");

                    b.HasIndex("SizeMetricId");

                    b.HasIndex(new[] { "Value" }, "IX_Sizes_Name")
                        .IsUnique();

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.SizeMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("Name")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK_Metrics");

                    b.HasIndex(new[] { "Name" }, "IX_SizeMetrics_Name")
                        .IsUnique();

                    b.ToTable("SizeMetrics");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.SkinType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_SkinTypes_Name")
                        .IsUnique();

                    b.ToTable("SkinTypes");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.Brand", b =>
                {
                    b.HasOne("Shoe_restoration_project.Models.Country", "Country")
                        .WithMany("Brands")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK_Brands_Countries");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.MeasurementValue", b =>
                {
                    b.HasOne("Shoe_restoration_project.Models.MeasurementMetric", "MeasurementMetric")
                        .WithMany("MeasurementValues")
                        .HasForeignKey("MeasurementMetricId")
                        .IsRequired()
                        .HasConstraintName("FK_Measurement_Values_Measurement_Metrics");

                    b.Navigation("MeasurementMetric");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.Shoe", b =>
                {
                    b.HasOne("Shoe_restoration_project.Models.Brand", "Brand")
                        .WithMany("Shoes")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FK_Shoes_Brands");

                    b.HasOne("Shoe_restoration_project.Models.Color", "Color")
                        .WithMany("Shoes")
                        .HasForeignKey("ColorId")
                        .IsRequired()
                        .HasConstraintName("FK_Shoes_Colors");

                    b.HasOne("Shoe_restoration_project.Models.Condition", "Condition")
                        .WithMany("Shoes")
                        .HasForeignKey("ConditionId")
                        .IsRequired()
                        .HasConstraintName("FK_Shoes_Conditions");

                    b.HasOne("Shoe_restoration_project.Models.ShoeType", "ShoeType")
                        .WithMany("Shoes")
                        .HasForeignKey("ShoeTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Shoes_Shoe_Types");

                    b.HasOne("Shoe_restoration_project.Models.Size", "Size")
                        .WithMany("Shoes")
                        .HasForeignKey("SizeId")
                        .IsRequired()
                        .HasConstraintName("FK_Shoes_Sizes");

                    b.HasOne("Shoe_restoration_project.Models.SkinType", "SkinType")
                        .WithMany("Shoes")
                        .HasForeignKey("SkinTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Shoes_Skin_Types");

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Condition");

                    b.Navigation("ShoeType");

                    b.Navigation("Size");

                    b.Navigation("SkinType");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.ShoeImage", b =>
                {
                    b.HasOne("Shoe_restoration_project.Models.Shoe", "Shoe")
                        .WithMany("ShoeImages")
                        .HasForeignKey("ShoeId")
                        .IsRequired()
                        .HasConstraintName("FK_Shoe_Images_Shoes");

                    b.Navigation("Shoe");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.ShoeMeasurement", b =>
                {
                    b.HasOne("Shoe_restoration_project.Models.MeasurementProperty", "MeasurementProperty")
                        .WithMany("ShoeMeasurements")
                        .HasForeignKey("MeasurementPropertyId")
                        .IsRequired()
                        .HasConstraintName("FK_Shoe_Measurements_Measurement_Properties");

                    b.HasOne("Shoe_restoration_project.Models.MeasurementValue", "MeasurementValue")
                        .WithMany("ShoeMeasurements")
                        .HasForeignKey("MeasurementValueId")
                        .IsRequired()
                        .HasConstraintName("FK_Shoe_Measurements_Measurement_Values");

                    b.HasOne("Shoe_restoration_project.Models.Shoe", "Shoe")
                        .WithMany("ShoeMeasurements")
                        .HasForeignKey("ShoeId")
                        .IsRequired()
                        .HasConstraintName("FK_Shoe_Measurements_Shoes");

                    b.Navigation("MeasurementProperty");

                    b.Navigation("MeasurementValue");

                    b.Navigation("Shoe");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.Size", b =>
                {
                    b.HasOne("Shoe_restoration_project.Models.SizeMetric", "SizeMetric")
                        .WithMany("Sizes")
                        .HasForeignKey("SizeMetricId")
                        .IsRequired()
                        .HasConstraintName("FK_Sizes_Size_Metrics");

                    b.Navigation("SizeMetric");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.Brand", b =>
                {
                    b.Navigation("Shoes");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.Color", b =>
                {
                    b.Navigation("Shoes");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.Condition", b =>
                {
                    b.Navigation("Shoes");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.Country", b =>
                {
                    b.Navigation("Brands");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.MeasurementMetric", b =>
                {
                    b.Navigation("MeasurementValues");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.MeasurementProperty", b =>
                {
                    b.Navigation("ShoeMeasurements");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.MeasurementValue", b =>
                {
                    b.Navigation("ShoeMeasurements");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.Shoe", b =>
                {
                    b.Navigation("ShoeImages");

                    b.Navigation("ShoeMeasurements");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.ShoeType", b =>
                {
                    b.Navigation("Shoes");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.Size", b =>
                {
                    b.Navigation("Shoes");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.SizeMetric", b =>
                {
                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("Shoe_restoration_project.Models.SkinType", b =>
                {
                    b.Navigation("Shoes");
                });
#pragma warning restore 612, 618
        }
    }
}
